version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net

  backend:
    image: 105417736896.dkr.ecr.eu-west-2.amazonaws.com/fullstack-backend
    environment:
      POSTGRES_PASSWORD: example
    depends_on:
      - db
    networks:
      - app-net
    deploy:
      replicas: 1
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host

  frontend:
    image: 105417736896.dkr.ecr.eu-west-2.amazonaws.com/fullstack-frontend
    networks:
      - app-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
      - target: 80
        published: 3000
        protocol: tcp
        mode: host

volumes:
  pgdata:

networks:
  app-net:
